### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by kaoru-nishida** [Ogiwara-CostlierRain464/LobiClient#1]
Using kotlin incremental compilation
e: /home/tomo/Downloads/LobiClient-master/app/src/main/java/jp/ogiwara/test/lobitest/ThisApplication.kt: (13, 48): No value passed for parameter 'realm'
:app:compileDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 6.276 secs

OS : Ubuntu
gradle : 3.4

**Comment by Ogiwara-CostlierRain464** [comment]
Githubにはまだ修正版上げてない()

**Comment by Ogiwara-CostlierRain464** [comment]
修復したよ!
